[package]
name = "krust"
version = "0.1.0"
authors = ["Grainne Henderson <grainnehenderson@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.3.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "arm-krust.json"