[package]
name = "krust"
version = "0.1.0"
authors = ["Grainne Henderson <grainnehenderson@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.3.4"
volatile = "0.2.3"
spin = "0.4.9"
uart_16550 = "0.1.0"
x86_64 = "0.2.8"
pic8259_simple = "0.1.1"
pc-keyboard = "0.3.1"
# Math library
# m = "0.1.1"
# FAT32 filesystem
# fatfs = "0.3"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-krust.json"